// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {

    repositories {

        google() // Add google Maven repository here
        mavenCentral()

    }

    dependencies {

        classpath 'com.android.tools.build:gradle:8.10.1' // Define the AGP version

    }

}

plugins {

    alias(libs.plugins.android.application) apply false

}