/*
This program (The Chameleon Mini Live Debugger) is free software written by
Maxie Dion Schmidt: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

The complete license provided with source distributions of this library is
available at the following link:
https://github.com/maxieds/ChameleonMiniLiveDebugger
*/

apply plugin: 'com.android.application'

import java.text.DateFormat
import java.text.SimpleDateFormat

def getDateTimestamp() {

    DateFormat df = new SimpleDateFormat("YYYY-MM-dd-HHmmss")
    return new String(df.format(new Date()).toString())

}

def getVersionNameFull(String versionNameBase, String versionNameType) {

    if (!versionNameType.equals("") && !versionNameType.toLowerCase().equals("release")) {
        return String.format(Locale.getDefault(), "%s-%s", versionNameBase, versionNameType)
    } else {
        return versionNameBase
    }

}

def getShellCommandOutput(String shellCmd) {
    try {
        def cmdResult = ['bash', '-c', shellCmd].execute();
        int waitResult = cmdResult.wait();
        if (cmdResult.text.length() == 0) {
            return '';
        }
        String cmdResultText = cmdResult.text;
        return cmdResultText.substring(0, cmdResultText.length() - 1);
    } catch (Exception streamError) {
        streamError.printStackTrace();
        return '';
    }
}

def getGitCommitHash() {

    return getShellCommandOutput("git show | head -n 1 | sed -e \"s/commit //\" | cut -c-12")

}

def getGitCommitDate() {

    return getShellCommandOutput("git show | grep Date: | head -n 1 | sed -e \"s/Date:[ ]*//\"")

}

/* INFO: The gradle plugin with Android does not work, this is a shell command within the
 *       standard system paths (make sure the antlr -- version 4.x.x -- command binary version matches
 *       the runtime version in the implementation line below, or you will get errors).
 */
def generateAntlrJava(String grammarFile) {
    /* NOTE: The ``antlr4`` command is aliased in my bash profile.
     *       The standard name for this command is ``antlr``.
     */
    String ANTLR4_CMD_NAME = "antlr4";
    String scriptRunCmdFmt = "%s -o app/src/main/antlr-gen -package 'com.maxieds.chameleonminilivedebugger.ScriptingAPI' -Dlanguage=Java" +
            " -listener -visitor -long-messages -lib 'app/src/main/java/com/maxieds/chameleonminilivedebugger/ScriptingAPI'" +
            " -Xexact-output-dir 'app/src/main/java/com/maxieds/chameleonminilivedebugger/ScriptingAPI/%s'"
    String scriptRunCmd = String.format(Locale.getDefault(), scriptRunCmdFmt, ANTLR4_CMD_NAME, grammarFile)
    try {
        def cmdResult = ['bash', '-c', scriptRunCmd].execute()
        int waitResult = cmdResult.wait()
        String cmdResultText = cmdResult.text
        if (cmdResultText.length() == 0) {
            return ''
        }
        return cmdResultText
    } catch (Exception streamError) {
        streamError.printStackTrace()
        return ''
    }
}

task cleanBuildDir {

    delete rootProject.buildDir

}
clean.dependsOn cleanBuildDir

task cleanPreBuildGenAntlr4JavaSources {

    println '==> REMOVING OLD ANTLR4 JAVA SOURCES ...'
    file(new File('app/src/main/antlr-gen')).deleteDir()
    println '==> GENERATING ANTLR4 JAVA SOURCES ...'
    file(new File('app/src/main/antlr-gen')).mkdirs()
    generateAntlrJava("ChameleonScriptLexer.g4")
    generateAntlrJava("ChameleonScriptParser.g4")

}
clean.dependsOn cleanPreBuildGenAntlr4JavaSources

task verboseBuildLogs {

    logging.captureStandardOutput LogLevel.DEBUG

}
preBuild.dependsOn verboseBuildLogs

task preBuildGenAntlr4JavaSources {

    println '==> REMOVING OLD ANTLR4 JAVA SOURCES ...'
    file(new File('app/src/main/antlr-gen')).deleteDir()
    println '==> GENERATING ANTLR4 JAVA SOURCES ...'
    file(new File('app/src/main/antlr-gen')).mkdirs()
    generateAntlrJava("ChameleonScriptLexer.g4")
    generateAntlrJava("ChameleonScriptParser.g4")
    /* Make the task run every time (no UP-TO-DATE skipping): */
    outputs.upToDateWhen { false }

}
preBuild.dependsOn cleanBuildDir
preBuild.dependsOn preBuildGenAntlr4JavaSources

android {

    int versionCodeBase = 8080
    int versionCodeRevision = 132
    String appNamespace = 'com.maxieds.chameleonminilivedebugger'
    String versionNameBase = "1.6.4"
    String versionNameType = "pro(d)"
    String configBuildTimeStamp = getDateTimestamp()

    namespace appNamespace
    compileSdk 35
    compileSdkVersion 35

    defaultConfig {

        applicationId appNamespace
        versionCode versionCodeRevision + versionCodeBase

        minSdkVersion 29
        targetSdkVersion 35
        versionCode versionCodeRevision + versionCodeBase
        //versionName getVersionNameFull(versionNameBase, versionNameType)
        versionName versionNameBase
        buildFeatures.buildConfig = true
        buildToolsVersion '35.0.1'
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "GIT_COMMIT_HASH", "\"" + getGitCommitHash() + "\""
        buildConfigField "String", "GIT_COMMIT_DATE", "\"" + getGitCommitDate() + "\""
        buildConfigField "int", "VERSION_CODE_BASE", String.format(Locale.getDefault(), "%d", versionCodeBase)
        buildConfigField "java.util.Locale", "DEFAULT_LOCALE", "java.util.Locale.ENGLISH"
        buildConfigField "java.nio.charset.Charset", "DEFAULT_CHARSET", "java.nio.charset.StandardCharsets.UTF_8"
        setProperty("archivesBaseName", "ChameleonMiniLiveDebugger-v$versionName-$versionCode-$configBuildTimeStamp")

    }

    compileOptions {

        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17

    }

    lint {

        abortOnError = false
        checkAllWarnings = true
        explainIssues = true
        ignoreWarnings = false
        warningsAsErrors = false

    }

    sourceSets {

        main {

            java {

                srcDirs = [ 'src/main/java', 'src/main/antlr-gen' ]

            }

        }

    }

    buildTypes {

        release {

            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            crunchPngs false
            debuggable false

        }

        debug {

            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            crunchPngs false
            debuggable true

        }

    }

    flavorDimensions "mode"

    productFlavors {

        free {

            versionNameSuffix   "-free"

            dimension "mode"

            buildConfigField "String",             "BUILD_TIMESTAMP", "\"" + configBuildTimeStamp + "\""
            buildConfigField "boolean",            "PAID_APP_VERSION", "false"

            resConfigs 'en', 'en_US', 'en_UK', 'de', 'fr', 'ru'

            manifestPlaceholders = [
                    appLabelDesc       : "@string/app_display_short_name",
                    appIcon            : "@mipmap/chameleon_app_icon_round",
                    appRoundIcon       : "@mipmap/chameleon_app_icon_round",
                    appTheme           : "@style/AppThemeGreen",
                    appDebug           : "false",
                    installLocation    : "auto"
            ]

        }

        paid {

            applicationIdSuffix ".paid"
            versionNameSuffix   "-paid"

            dimension "mode"

            buildConfigField "String",             "BUILD_TIMESTAMP", "\"" + configBuildTimeStamp + "\""
            buildConfigField "boolean",            "PAID_APP_VERSION", "true"

            resConfigs 'en', 'en_US', 'en_UK', 'de', 'fr', 'ru'

            manifestPlaceholders = [
                    appLabelDesc       : "@string/app_display_short_name_paid",
                    appIcon            : "@mipmap/chameleon_app_icon_round_paid",
                    appRoundIcon       : "@mipmap/chameleon_app_icon_round_paid",
                    appTheme           : "@style/AppThemeGreenPaid",
                    appDebug           : "false",
                    installLocation    : "auto"
            ]

        }

    }

    dependencies {

        /* Jitpack.io has spotty configuration that prevents
         * resolving imports of the form: com.maxieds.androidfilepickerlightlibrary.
         * WORKAROUND: Build the library as a AAR file, stash it in _libs/* and
         *             include the AAR from there.
         */
        //implementation 'com.github.maxieds:AndroidFilePickerLight:release-v22'
        //implementation 'com.github.maxieds:AndroidFilePickerLight:master-SNAPSHOT'

        /* The AndroidFilePickerLightLibrary AAR is not a "fat-AAR",
         * meaning all of its dependencies are not bundled in the
         * library file. We're going to use the next workaround by
         * including all the sub-library dependencies of AFPL:
         */
        implementation 'androidx.appcompat:appcompat:1.4.2'
        implementation 'androidx.recyclerview:recyclerview:1.2.1'
        implementation 'org.apache.commons:commons-text:1.7'
        implementation 'pub.devrel:easypermissions:3.0.0'

        implementation fileTree(include: ['*.jar'], dir: '_libs')
        implementation fileTree(include: ['*.aar'], dir: '_libs')

        implementation 'com.android.support.constraint:constraint-layout:2.0.2'
        implementation 'androidx.legacy:legacy-support-v4:1.0.0'
        implementation 'androidx.appcompat:appcompat:1.2.0'
        implementation 'com.google.android.material:material:1.3.0-beta01'
        implementation 'org.apache.commons:commons-text:1.7'
        implementation 'org.antlr:antlr4:4.9.2'
        implementation 'org.antlr:antlr4-runtime:4.9.2'
        implementation 'com.github.felHR85:UsbSerial:6.1.0' // older: 4.5.2
        implementation 'com.github.shawnlin013:NumberPicker:v2.4.12'

        testImplementation 'junit:junit:4.13.2'
        androidTestImplementation 'androidx.test:core:1.5.0'
        androidTestImplementation 'androidx.test.ext:junit:1.1.5'

    }

}
dependencies {
    implementation files('../_libs/AndroidFilePickerLightLibrary-release-1.4.0-beta.aar')
}
